import React from "react";

export default function Home() {
  return (
    <main style={{ maxWidth: "700px", margin: "0 auto" }}>
      <h1 style={{ color: "#38bdf8" }}>⚡ x402-Protected API Template</h1>
      <p style={{ fontSize: "1.1rem", lineHeight: "1.6" }}>
        Welcome to your live x402 micro-payment API powered by <strong>Nirium SDK</strong> and <strong>Vercel</strong>.
      </p>

      <section style={{ background: "#1e293b", padding: "1.5rem", borderRadius: "8px", marginTop: "1.5rem" }}>
        <h2>Available Endpoints</h2>
        <ul>
          <li>
            <code>GET /api/ascii</code> — Generates ASCII art (requires $0.01 USDC x402 payment).
          </li>
        </ul>
      </section>

      <section style={{ background: "#1e293b", padding: "1.5rem", borderRadius: "8px", marginTop: "1.5rem" }}>
        <h2>How to Test</h2>
        <p>1. Test 402 Payment Required response:</p>
        <pre style={{ background: "#090d16", padding: "1rem", borderRadius: "6px", overflowX: "auto" }}>
          curl -i http://localhost:3000/api/ascii
        </pre>
        <p>2. Pay and request using Nirium CLI or SDK:</p>
        <pre style={{ background: "#090d16", padding: "1rem", borderRadius: "6px", overflowX: "auto" }}>
          nirium pay http://localhost:3000/api/ascii
        </pre>
        <p>Or send a valid <code>PAYMENT-SIGNATURE</code> header generated by an x402 client.</p>
      </section>
    </main>
  );
}
